### ISSUE TITLE
Removing rows with NA for Client.ID

### ISSUE THREAD

**Issue by nicklucius** [Chicago/e-coli-beach-predictions#115]
The [code](https://github.com/Chicago/e-coli-beach-predictions/blob/master/Master.R#L9-L10) in `Master.R` removes each row where Client.ID is NA. A lot of these rows have E. Coli readings. 

Are these listed as NA for Client.ID in the data portal? If so, do we have better data in the `hacknight` branch? Maybe there is just an issue with the data portal data.

**Comment by CallinOsborn** [comment]
These NA for Client.ID comes in from when we do the clean of the beach names.  For example, in 2016 we have readings for the Montrose Dog Beach.  In the `cleanbeachnames.csv` we have that set to going to NA. There are some beaches that are now defunct, etc.  If we want to look into what we are changing to NA we can, otherwise we have all the information for the beaches we are predicting in `df`.
