### ISSUE TITLE
Gather river lock openings

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#12]
The dates of when the lock between the beach and river is open

**Comment by emchandler** [comment]
As far as I've found out, there are two locks for watercraft. Looking at the traffic through the Navy Pier lock, we can probably approximate it as always open during the warm months, because they let traffic through 11k times per year (http://www.navigationdatacenter.us/lpms/lpms.htm). More detailed traffic reports are only available online for the last 30 days (http://corpslocks.usace.army.mil/lpwb/f?p=121:7:0) but I bet we could get historical data if we really want it -- the latter web service only provides snapshots (http://www.navigationdatacenter.us/lpms/locksannouncement.pdf).

I haven't found if/when the locks shut down for the winter or open for the spring. There are also water intake stations in Wilmette and Evanston that I don't know much about.

**Comment by tomschenkjr** [comment]
They'll keep the locks closed unless they need to empty water into the lake. The two locks aren't opened at the same time for traffic, they'll use it as a fixed chamber to lower or raise boats since the water levels aren't the same.

**Comment by tomschenkjr** [comment]
I'll work on parsing this into machine readable.
[Reversals.pdf](https://github.com/tomschenkjr/e-coli-beach-predictions/files/22122/Reversals.pdf)

**Comment by fgregg** [comment]
dope!

**Comment by tomschenkjr** [comment]
[Interesting fact](http://il.water.usgs.gov/publications/abstract.php?series=WRIR&number=94-4112) (emphasis mine):

> Acoustic Doppler current profilers (ADCP's) and dye-dilution techniques were used to make 221 measurements of leakage at three control structures near Chicago, Ill. The three control structures are the Chicago River Controlling Works (CRCW), Thomas J. O'Brien Lock and Dam (O'Brien), and Wilmette Pumping Station (Wilmette). The CRCW consists of the Chicago Lock and two sets of sluice gates connected by a network of harbor walls. **Lake Michigan water leaks through harbor walls, lock gates, and sluice gates at each of these control structures.** The diversion of Lake Michigan water is regulated by U.S. Supreme Court decree, and the water leaking through each of these structures forms part of the diversion of Lake Michigan water by the State of Illinois.
