### ISSUE TITLE
Reading 1 and Reading 2 are blank, but geometric means are provided

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#21]
Why does this happen?

**Comment by mattesweeney** [comment]
I realized that this issue is due to column name differences -- most of these occur in 2014 where after June 16 "Readings" mostly change to "Samples," and in R I have NAs for all "Sample" columns although the values are there in the excel files. I have already fixed this issue for 2014 so now there are very few geometric means without Readings, and will update code to handle column name errors like this for 2006 to 2015

**Comment by tomschenkjr** [comment]
Thanks. Closing the issue.
