### ISSUE TITLE
Some sheets have more than 2 readings

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#34]
I found a few sheets that have more than 2 readings. It looks like the R code does not handle these (it silently renames the extra reading columns). This could possibly related to the large outlier? Could also be causing the few instances where we observed a larger-than-1 difference between our calculated geometric mean and the geometric mean we pulled from the excel file (i.e. by renaming the column `Reading 3` to `Escherichia.coli`)

Found these dates on a first-pass through:

```
July 31 2006
August 1 2006
August 2 2006
August 3 2006
August 4 2006
August 9 2006
August 2 2007
August 2 2008
```

**Comment by mattesweeney** [comment]
Thanks for documenting these -- we discussed them a few weeks back, although I'm not sure if we decided on a solution. There are other issues with the Escherichia.coli variable (i.e. the values are truncated instead of rounded when read into R) so we are not using it. We've actually re-created this variable (named e.coli.geomean) using Reading.1 and Reading.2.  

We considered excluding any date with more than 2 readings or using just the first two readings to create its e.coli.geomean.

**Comment by kbrose** [comment]
Yeah, I'm not particularly worried about just throwing out the extra readings since it happened so few times. I don't think the R code handles these few cases, though, and will effectively shift all of the other columns off of their actual names by one. Since those columns are information that, to my knowledge, is never used, I'll just go ahead and close the issue.
