### ISSUE TITLE
Use data mining to help identify useful variables

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#42]
@nicklucius is using PCA to determine some predictors.

**Comment by kbrose** [comment]
Adding on the possibility of using LDA ([https://en.wikipedia.org/wiki/Linear_discriminant_analysis](https://en.wikipedia.org/wiki/Linear_discriminant_analysis)).

**Comment by nicklucius** [comment]
## Results of Principal Component Analysis (PCA)

I performed PCA on all numeric variables that we have, except a few that were problematic (e.g. Transducer Depth variables have few if any values). 

Principal Components (PC) 1 and 2 accounted for most of the variance in the data, as the following graph shows. I chose to look at PCs 1 and 2 for that reason.

<img width="799" alt="pca graph" src="https://cloud.githubusercontent.com/assets/16853555/13380848/28cea0d6-de12-11e5-913d-23bf0f8da196.png">

The following tables show how much each variable contributed to PCs 1 and 2. Below, the first table is sorted descending by PC 1, and the second is the same data sorted descending by PC 2. The values for each PC’s rows add up to 1.

**PC 1 Contributing Variables**

<img width="441" alt="pc 1" src="https://cloud.githubusercontent.com/assets/16853555/13380858/5edc23f6-de12-11e5-9d8c-68c7002ec167.png">

**PC 2 Contributing Variables**

<img width="437" alt="pc 2" src="https://cloud.githubusercontent.com/assets/16853555/13380862/6593b056-de12-11e5-834d-8142edce4097.png">

The variables that contribute the most to PC 1 are those related to air temp, length of day, water temp, rain, and humidity.

PC 2 is affected most by rain metrics, air pressure, length of day, and air temperature.

So the most variance in our data seems to occur in air/water temp, rain,  length of day, humidity, and air pressure measurements.

The number of days since the last holiday also shows up as a contributing factor to the PCs. It’s worth mentioning that there are variables that we think might be important that do not vary widely and therefore do not appear here, such as day of week and lock openings.

@kbrose  mentioned at a recent meeting that Linear Discriminant Analysis (LDA) could be more useful than PCA. PCA looks for the most variation among all variables, but with LDA you can classify your variables and then look for meaningful variations between the classes. Using LDA, we could put E. Coli reading variables in one class, and then see what relationships exist between the E. Coli reading data and some other class of variables. Next I’ll try to do LDA analysis to look for combinations of variables to plug into our models.

**Comment by tomschenkjr** [comment]
This is great. Is this based on the prior reading?

**Comment by nicklucius** [comment]
I ran it with a few different combinations of prior readings or prior weather data. I think these results are using same day readings, and the same day geometric mean too. The results were essentially the same across combinations, but I will run it with a few defined combinations and see if we get different results and share them. 

Since there are so many variables, the typical weather measurements seem to overshadow any other data relationships because they are related. Examples could be that the temp goes up after sunrise and down after sunset, and low pressures are correlated with storms. I think the LDA could give more insight to which variables might affect the reading levels more than others.

**Comment by tomschenkjr** [comment]
Same day readings might be out-of-sequence since the weather is being reported later than the readings. E.g., readings at 8:30a and max temp is at 3p.

Were the prior-day reading results similar to the same-day results?

**Comment by nicklucius** [comment]
Makes sense, I'll check and report back.

**Comment by nicklucius** [comment]
Found similar results when running PCA on E. Coli readings in conjunction with the weather from the day before the reading. One difference is that turbidity and cloud cover moved up in the rankings.

![pc1](https://cloud.githubusercontent.com/assets/16853555/13417509/4899c03c-df32-11e5-8d68-66ec91ee2286.jpg)

![pc2](https://cloud.githubusercontent.com/assets/16853555/13417544/907bf24e-df32-11e5-9e6c-c19e1f23d51c.jpg)

**Comment by tomschenkjr** [comment]
@nicklucius is going to do some linear discriminate analysis (LDA) to identify variables/levels.
