### ISSUE TITLE
Reconcile Python and R code semantics and names

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/e-coli-beach-predictions#50]

**Comment by kbrose** [comment]
This includes the following
- column to include (specifically weather and water sensor data)
- column names (including the names of "shifted" columns)
- decide how the shifting is done (taking the previous reading, independent of whether it was from yesterday or from 3 days ago (e.g. Monday to last Friday))

**Comment by kbrose** [comment]
More on bullet 3, @nicklucius, @beckeroobonsai and I were discussing last night, and I don't remember if we reached a consensus, but I think we were leaning towards just taking the previous reading, no matter how many days in the past it was (at least, that's the direction I was leaning).

This can get slightly more complicated once we have downloaded the additional weather data from issue #58. It would be possible for the "previous" weather data to be from yesterday, but the "previous" E. coli readings to come from two or three days ago (e.g. for a Monday, we have weather from Sunday, but don't have E. coli readings for Saturday or Sunday). I think it still makes sense to take the most recent reading that is not NA as the "previous" reading, but we should probably discuss this more.

**Comment by nicklucius** [comment]
I am leaning in the same direction as @kbrose on bullet 3. At a recent meeting, @tomschenkjr ran an analysis that showed the vast majority of beaches had readings everyday or almost everyday. 

The R version of the shifting function groups the data by year and beach, sorts by date, and then for each of these "beach years" iterates through row. For the first n rows (n being the number of observations to look backward for the new column), the function outputs NA into the new shifted column since there is no prior data to use. If we get weather data for the week prior to the first reading, I could change it to use that data.

Also, the R function allows the user to create new shifted columns for more than one variable, and by default will create a new shifted column for every numeric column in the dataset. The new shifted columns look backward n days, no matter whether the readings are NA. Because it can shift multiple columns, it would be hard to skip NA data unless all data for a new shifted column would be NA. One way to deal with NA issues would be to call the function for multiple values of n and use the results in a model.

**Comment by tomschenkjr** [comment]
@nicklucius is going to adjust the R code to read-in like the Python code created by @beckeroobonsai. Namely, to include the lag _n_ within the variable name to show the amount of the shift.
