### ISSUE TITLE
What is an acceptable False Positive Rate?

### ISSUE THREAD

**Issue by kbrose** [Chicago/e-coli-beach-predictions#85]
Using a threshold of 235.0 on the EPA model results in a FPR of about 1.2%, but a TPR of only about 7% (!!!).

What would be considered an allowable False Positive Rate? Knowing this range would allow us to use a [partial AUC (pAUC)](https://en.wikipedia.org/wiki/Receiver_operating_characteristic#Other_measures) measurement that would be more informative than using the AUC over the entire range of FPRs, including those we would never use.

Below is an example of an ROC curve, with the large **X** in the lower left corner representing the performance of the EPA model using a threshold of 235. If the maximum allowable FPR is only at around 2%, then this graph is showing a lot of unnecessary information.

![roc](https://cloud.githubusercontent.com/assets/4053170/14224082/2cfa5760-f855-11e5-9b1d-a7db70f383a2.png)

**Comment by kbrose** [comment]
Sample of what a partial ROC curve (cut-off at FPR of 10%) could look like:

![partial_roc](https://cloud.githubusercontent.com/assets/4053170/14224188/46190120-f859-11e5-82cb-5254b0470eed.png)

**Comment by tomschenkjr** [comment]
Let me check with Parks on any targets they may have.

**Comment by ZombieSocrates** [comment]
Just something that I was thinking about today:  In terms of the types of errors our models can make, wouldn't we be way more concerned about false negatives?  Isn't it worse to say "The beach is fine" when it actually isn't, because then you're (potentially) exposing people to getting sick?

The ROC curves, while certainly still informative, won't really tell us anything about false negatives, so I was just wondering if there's been any discussion on whether or not we should also look at precision/recall/f1 type metrics as well?

**Comment by kbrose** [comment]
Isn't the `False Negative Rate` just `1 - True Positive Rate`? But yes, I have also been plotting the Precision-Recall graph, I have not been uploading them because they generally tell the same story as the ROC curve.

Determining which mistake (false negative vs. false positive) is more costly is dependent on a lot of things. Even coming at the problem solely from a public health perspective I'm not convinced that valuing the TPR over the FPR is the right decision. A very high FPR would most likely decrease the importance the public gives to a swim advisory (if there's a swim advisory every other day, it will most likely be ignored altogether, e.g. The Boy Who Cried Wolf).

[The paper on the wiki page](https://github.com/Chicago/e-coli-beach-predictions/wiki/Research-Notes#relevant-paper-economic-and-health-risk-trade-offs-of-swim-closures) is trying to measure the trade-off from an economical point of view. I think there are a lot of things that are wrong/irrelevant to our situation in the paper, but is a good jumping off point. Unfortunately, the paper misses a lot of sociological factors that are just as (if not more) important in the decision making.

The problem is definitely worth thinking more about, however, and I'm hoping that Parks will have some insight in terms of their trade-offs.

**Comment by tomschenkjr** [comment]
Talked with some folks on this. They are aware of this potential, but not a solid answer to this yet. Will make most sense to run the pilot over the weekend and provide definitive answers (e.g., number of days) that would be impacted by adjusting the false positive rate.

**Comment by beckeroobonsai** [comment]
Last night at the chihacknight meetup we discussed how best to set a threshold for different models based on the holdout validation data.  The method that seems most appropriate is to take the threshold that keeps Precision at least as high as the current EPA model while maximizing Recall.  This would allow the most direct comparison of how we expect our model to perform.  

As for how the current EPA model is performing, is the cutoff 250 or 235? I just noticed that issue #74 says that the cutoff is 250. Tom, can you please confirm the 250 cutoff is what we should use?

Using that as the cutoff, the precision for 2015 was 42.3% and recall was 5.9%.   This means that of the 26 times that a warning was issued, the EPA model was correct only 42% of the time.  And of the 188 beach-days that there were E.Coli levels above 250, the model caught less than 6% of them.  This seems like a low bar for our model.  We'll see how it all turns out at the end of the summer.  

Does that sound like a good way to set our target threshold, setting it such that precision is at least 45% and recall is maximized (based on validation data)?
